[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate",
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "source .venv/bin/activate && python main.py"